ImgSave/ImgSave/Models/Img.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ImgSave.Models
{
    public class Img
    {
        [Key]
        public int Imgid { get; set; }
        public string Imgname { get; set; }
        public string Imgpath { get; set; }
    }
}

ImgSave/ImgSave/Controllers/ImgController.cs
using ImgSave.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.IO;

namespace ImgSave.Controllers
{

    public class ImgController : Controller
    {
        private readonly AppicationDbContext _adb;
        private readonly IWebHostEnvironment _iwebhost;
        public ImgController(AppicationDbContext adb, IWebHostEnvironment iwebhost)
        {
            _adb = adb;
            _iwebhost = iwebhost;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Index(IFormFile ifile, Img ic)
        {
            string imgext = Path.GetExtension(ifile.FileName);
            if (imgext == ".jpg" || imgext == ".gif" || imgext == ".png" || imgext == ".pdf" || imgext == ".jpeg")
            {
                var saveimg = Path.Combine(_iwebhost.WebRootPath, "Images", ifile.FileName);
                var stream = new FileStream(saveimg, FileMode.Create);
                await ifile.CopyToAsync(stream);


                ic.Imgname = ifile.FileName;
                ic.Imgpath = saveimg;
                await _adb.imagesave.AddAsync(ic);
                await _adb.SaveChangesAsync();
                ViewData["Message"] = "The selected  file is saved!";
            }
            else
            {
                ViewData["Message"] = "Please upload only .jpg,.png and .gif only";
            }
            return View();


        }
        [HttpGet]
        public IActionResult List()
        {

            return View(_adb.imagesave.ToList());
        }
    }
}

ImgSave/ImgSave/Views/Img/Index.cshtml
@{
    ViewData["Title"] = "Index";
}
<form method="post" enctype="multipart/form-data" asp-controller="Img" asp-action="Index">
    <input type="file" name="ifile"/>

    <input type="submit" value="Upload.."/>

    <hr />
    <h4>
        @ViewData["Message"]
    <h3>Swagger api is running</h3>
    </h4>
</form>

ImgSave/ImgSave/Views/Img/List.cshtml
@model IEnumerable<ImgSave.Models.Img>

@{
    ViewData["Title"] = "List";
}

<h1>List</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Imgname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imgpath)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Imgname)
            </td>
            <td>
                <img src="~/Images/@item.Imgname" class="rounded-circle"
width="60" height="60" asp-append-version="true"  />      </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Imgid">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Imgid">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Imgid">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>